import './globals.css';
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </head>
          <body>
              <main>
                  <nav className="bg-blue-500 px-4 py-6 font-bold text-white">
                      <Link href="/" className='bg-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-blue-300 active:bg-blue-700 px-5 py-2 rounded-full hover:ease-in duration-300'>
                          Home
                      </Link>
                      <Link href="/timesheets" className='bg-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-blue-300 active:bg-blue-700 px-5 py-2 rounded-full hover:ease-in duration-300'>
                          Timesheets
                      </Link>
                  </nav>
                  {children}
              </main>
          </body>
      </html>
  )
}
